version: '3.8'

services:
  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - product-service
      - user-service
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network

  user-service:
    build: ./user-service
    ports:
      - "8083:8083"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
